# Generated by Django 2.1.5 on 2019-08-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.IntegerField(choices=[(-1, 'not define'), (0, 'POP'), (1, 'rock')], default=-1),
        ),
        migrations.AddField(
            model_name='band',
            name='still_active',
            field=models.BooleanField(default=True),
        ),
    ]
