# Generated by Django 2.1.5 on 2019-08-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20190806_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(0, 'one'), (1, 'two'), (2, 'smash'), (3, 'overwatch'), (4, '')])),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exercises.Band')),
            ],
        ),
    ]
