# Generated by Django 2.1.5 on 2019-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='name',
        ),
        migrations.AddField(
            model_name='album',
            name='title',
            field=models.CharField(default='', max_length=124),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.IntegerField(choices=[(1, 'BAD'), (2, 'NOT SO BAD'), (3, 'EEE'), (4, 'GOOD'), (5, 'VERY GOOOOOD')]),
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.IntegerField(choices=[(-1, 'fasdfasdfasd'), (0, 'POP'), (1, 'rock')], default=-1),
        ),
    ]
